/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gapabrikroti.view;

import gapabrikroti.controller.KoordinatController;
import gapabrikroti.dao.KoordinatDAO;
import gapabrikroti.error.EvaluasiGenerationException;
import gapabrikroti.error.KoordinatException;
import gapabrikroti.model.Koordinat;
import gapabrikroti.service.KoordinatService;
import gapabrikroti.service.KoordinatServiceImpl;
import gapabrikroti.service.KoordinatServiceTable;
import gapabrikroti.utility.databaseUtility;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.openstreetmap.gui.jmapviewer.Coordinate;
import org.openstreetmap.gui.jmapviewer.JMapViewer;



/**
 *
 * @author cvgs
 */
public class KoordinatView extends javax.swing.JFrame implements KoordinatService, ListSelectionListener { 

    /**
     * Creates new form view_koordinat
     */
    private KoordinatServiceTable koordinatServiceTable;
    private KoordinatServiceImpl koordinatServiceImpl;
    private KoordinatController koordinatController;
    
    public KoordinatView() throws SQLException, KoordinatException {
        koordinatServiceImpl = new KoordinatServiceImpl();
        koordinatServiceImpl.setKoordinatService(this);

        koordinatController = new KoordinatController();
        koordinatController.setKoordinat(koordinatServiceImpl);

        koordinatServiceTable = new KoordinatServiceTable();
        
        initComponents();
        
        tblKoordinat.getSelectionModel().addListSelectionListener(this);
        tblKoordinat.setModel(koordinatServiceTable);

        loadTblKoordinat();
        
        labelId.setVisible(false);
        textId.setVisible(false);
        
        labelId.setEnabled(false);
        textId.setEnabled(false);
        
    }

    public JTextField getTextBobot() {
        return textBobot;
    }

    public JTextField getTextX() {
        return textX;
    }

    public JTextField getTextY() {
        return textY;
    }

    public JTextField getTextId() {
        return textId;
    }

    public JTable getTblKoordinat() {
        return tblKoordinat;
    }

    public void setTblKoordinat(JTable tblKoordinat) {
        this.tblKoordinat = tblKoordinat;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textX = new javax.swing.JTextField();
        textY = new javax.swing.JTextField();
        textBobot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKoordinat = new javax.swing.JTable();
        cmdDelete = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("x");

        jLabel2.setText("y");

        jLabel3.setText("bobot");

        textX.setName(""); // NOI18N

        jLabel4.setText("koordinat view");

        tblKoordinat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblKoordinat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKoordinat.setRowHeight(22);
        jScrollPane1.setViewportView(tblKoordinat);

        cmdDelete.setText("Delete");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });

        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        labelId.setText("id");

        jButton2.setText("min max peta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("peta koordinat awal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textBobot, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(cmdSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdReset))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelId)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textBobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdDelete)
                    .addComponent(cmdReset)
                    .addComponent(cmdUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        try {
            koordinatController.deleteKoordinat(this);
            loadTblKoordinat();
            tblKoordinat.setVisible(false);
            tblKoordinat.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
            labelId.setVisible(false);
            textId.setVisible(false);
        } catch (SQLException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (KoordinatException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdDeleteActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        try {
            koordinatController.resetKoordinat(this);
            loadTblKoordinat();
            tblKoordinat.setVisible(false);
            tblKoordinat.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
        } catch (SQLException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (KoordinatException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        }

    }//GEN-LAST:event_cmdResetActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        try {
            koordinatController.updateKoordinat(this);
            loadTblKoordinat();
            tblKoordinat.setVisible(false);
            tblKoordinat.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
            
        } catch (SQLException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (KoordinatException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        try {
            koordinatController.insertKoordinat(this);
            loadTblKoordinat();
            tblKoordinat.setVisible(false);
            tblKoordinat.setVisible(true);
        } catch (SQLException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (KoordinatException exception) {
            Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            createAndShowUIMinMax();
        } catch (SQLException ex) {
            Logger.getLogger(HasilIterasiView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (KoordinatException ex) {
            Logger.getLogger(HasilPerhitunganView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            createAndShowUIAkhirAwal();
        } catch (SQLException ex) {
            Logger.getLogger(HasilIterasiView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (KoordinatException ex) {
            Logger.getLogger(HasilPerhitunganView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (EvaluasiGenerationException ex) {
            Logger.getLogger(HasilPerhitunganView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KoordinatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KoordinatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KoordinatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KoordinatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KoordinatView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (KoordinatException ex) {
                    Logger.getLogger(KoordinatView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JTable tblKoordinat;
    private javax.swing.JTextField textBobot;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textY;
    // End of variables declaration//GEN-END:variables

    private void loadTblKoordinat() throws SQLException, KoordinatException {
        KoordinatDAO koordinatDAO = databaseUtility.getKoordinatDAO();
        koordinatServiceTable.setList(koordinatDAO.getAllKoordinat());

    }

    @Override
    public void onChange(KoordinatServiceImpl koordinatServiceImpl) {
        textId.setText(String.valueOf(koordinatServiceImpl.getId()));
        textX.setText(String.valueOf(koordinatServiceImpl.getX()));
        textY.setText(String.valueOf(koordinatServiceImpl.getY()));
        textBobot.setText(String.valueOf(koordinatServiceImpl.getBobot()));
        
        
    }

    @Override
    public void onInsert(Koordinat koordinat) {
        koordinatServiceTable.add(koordinat);
    }

    @Override
    public void onUpdate(Koordinat koordinat) {
        int index = tblKoordinat.getSelectedRowCount();
        koordinatServiceTable.set(index, koordinat);
    }

    @Override
    public void onDelete() {
        int index = tblKoordinat.getSelectedRowCount();
        koordinatServiceTable.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        Koordinat koordinat = koordinatServiceTable.get(e.getFirstIndex());
        textId.setText(String.valueOf(koordinat.getId()));
        textX.setText(String.valueOf(koordinat.getX()));
        textY.setText(String.valueOf(koordinat.getY()));
        textBobot.setText(String.valueOf(koordinat.getBobot()));
        labelId.setVisible(true);
        textId.setVisible(true);
    }

    private static void createAndShowUIMinMax() throws SQLException, KoordinatException {
        JFrame frame = new JFrame("Demo");
        JMapViewer viewer = new JMapViewer();

        List<Coordinate> coordinates = new ArrayList<Coordinate>();
        //membangkitkan evaluasi
        KoordinatDAO koordinatDAO = databaseUtility.getKoordinatDAO();
        
        double a1, a2, b1, b2, n, L, L1,L2;
        a1 = koordinatDAO.getMaxKoordinat().getXMin();
        a2 = koordinatDAO.getMaxKoordinat().getYMin();
        b1 = koordinatDAO.getMaxKoordinat().getXMax();
        b2 = koordinatDAO.getMaxKoordinat().getYMax();
        n  = 2;
        
        //System.out.println(a1 + " " + " " + a2 + " " + " " + b1 + " " + " " + b2);
        
        coordinates.add(new Coordinate(b1 - 25, a2 + 100));
        coordinates.add(new Coordinate(b1 - 25, b2 + 100));
        coordinates.add(new Coordinate(a1 - 25, b2 + 100));
        coordinates.add(new Coordinate(a1 - 25, a2 + 100));
        coordinates.add(new Coordinate(b1 - 25, a2 + 100));
        
        
        HasilIterasiView.MapPolyLine polyLine = new HasilIterasiView.MapPolyLine(coordinates);
        viewer.addMapPolygon(polyLine);

        frame.add(viewer);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationByPlatform(true);
        frame.pack();
        frame.setVisible(true);
    }
    
    private static void createAndShowUIAkhirAwal() throws SQLException, EvaluasiGenerationException, KoordinatException {
        JFrame frame = new JFrame("Demo");
        JMapViewer viewer = new JMapViewer();

        int x, y;

        KoordinatDAO KoordinatDAO;
        KoordinatDAO = databaseUtility.getKoordinatDAO();
        List<Koordinat> koordinat = KoordinatDAO.getAllKoordinat();
        List<Coordinate> coordinates = new ArrayList<Coordinate>();
        //membangkitkan evaluasi
        for (Koordinat itemkoordinat : koordinat) {
            x = (int) itemkoordinat.getX();
            y = (int) itemkoordinat.getY();
            coordinates.add(new Coordinate(x - 25, y + 100));
            //System.out.println(x + " " + " " + y);
        }

        HasilIterasiView.MapPolyLine polyLine = new HasilIterasiView.MapPolyLine(coordinates);
        viewer.addMapPolygon(polyLine);

        frame.add(viewer);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationByPlatform(true);
        frame.pack();
        frame.setVisible(true);
    }
}
