/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gapabrikroti.view;

import gapabrikroti.controller.ParameterController;
import gapabrikroti.dao.ParameterDAO;
import gapabrikroti.error.ParameterException;
import gapabrikroti.model.Parameter;
import gapabrikroti.service.ParameterService;
import gapabrikroti.service.ParameterServiceImpl;
import gapabrikroti.service.ParameterServiceTable;
import gapabrikroti.utility.databaseUtility;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author cvgs
 */
public class ParameterView extends javax.swing.JFrame implements ParameterService, ListSelectionListener{

    /**
     * Creates new form ParameterView
     */
    private ParameterServiceTable parameterServiceTable;
    private ParameterServiceImpl parameterServiceImpl;
    private ParameterController parameterController;
    
    public ParameterView() throws SQLException, ParameterException {
        parameterServiceImpl = new ParameterServiceImpl();
        parameterServiceImpl.setParameterService(this);

        parameterController = new ParameterController();
        parameterController.setParameter(parameterServiceImpl);

        parameterServiceTable = new ParameterServiceTable();
        
        initComponents();
        
        tblParameter.getSelectionModel().addListSelectionListener(this);
        tblParameter.setModel(parameterServiceTable);

        loadTblParameter();
        
        labelId.setVisible(false);
        textId.setVisible(false);
        
        labelId.setEnabled(false);
        textId.setEnabled(false);
        
        textNamaParameter.setEnabled(true);
    }

    public JTable getTblParameter() {
        return tblParameter;
    }

    public JTextField getTextId() {
        return textId;
    }

    public JTextField getTextNamaParameter() {
        return textNamaParameter;
    }

    public JTextField getTextNilai() {
        return textNilai;
    }

    public void setTblParameter(JTable tblParameter) {
        this.tblParameter = tblParameter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        textNamaParameter = new javax.swing.JTextField();
        textNilai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParameter = new javax.swing.JTable();
        cmdDelete1 = new javax.swing.JButton();
        cmdSimpan1 = new javax.swing.JButton();
        cmdReset1 = new javax.swing.JButton();
        cmdUpdate1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelId.setText("id");

        jLabel2.setText("nama parameter");

        jLabel3.setText("nilai");

        jLabel4.setText("Parameter View");

        tblParameter.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblParameter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblParameter.setRowHeight(22);
        jScrollPane1.setViewportView(tblParameter);

        cmdDelete1.setText("Delete");
        cmdDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDelete1ActionPerformed(evt);
            }
        });

        cmdSimpan1.setText("Simpan");
        cmdSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpan1ActionPerformed(evt);
            }
        });

        cmdReset1.setText("Reset");
        cmdReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReset1ActionPerformed(evt);
            }
        });

        cmdUpdate1.setText("Update");
        cmdUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(272, 272, 272))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNamaParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdUpdate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdDelete1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdReset1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNamaParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan1)
                    .addComponent(cmdDelete1)
                    .addComponent(cmdReset1)
                    .addComponent(cmdUpdate1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReset1ActionPerformed
        try {
            parameterController.resetParameter(this);
            loadTblParameter();
            tblParameter.setVisible(false);
            tblParameter.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
            textNamaParameter.setEnabled(true);
            textId.setText("");
            textNamaParameter.setText("");
            textNilai.setText("");
        } catch (SQLException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (ParameterException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdReset1ActionPerformed

    private void cmdUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdate1ActionPerformed
        try {
            parameterController.updateParameter(this);
            loadTblParameter();
            tblParameter.setVisible(false);
            tblParameter.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
            
        } catch (SQLException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (ParameterException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdUpdate1ActionPerformed

    private void cmdDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDelete1ActionPerformed
        try {
            parameterController.deleteParameter(this);
            loadTblParameter();
            tblParameter.setVisible(false);
            tblParameter.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);
            labelId.setVisible(false);
            textId.setVisible(false);

        } catch (SQLException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (ParameterException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdDelete1ActionPerformed

    private void cmdSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpan1ActionPerformed
        try {
            parameterController.insertParameter(this);
            loadTblParameter();
            tblParameter.setVisible(false);
            tblParameter.setVisible(true);
            labelId.setVisible(false);
            textId.setVisible(false);

        } catch (SQLException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (ParameterException exception) {
            Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdSimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParameterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParameterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParameterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParameterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ParameterView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParameterException ex) {
                    Logger.getLogger(ParameterView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete1;
    private javax.swing.JButton cmdReset1;
    private javax.swing.JButton cmdSimpan1;
    private javax.swing.JButton cmdUpdate1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JTable tblParameter;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNamaParameter;
    private javax.swing.JTextField textNilai;
    // End of variables declaration//GEN-END:variables

    private void loadTblParameter() throws SQLException, ParameterException {
        ParameterDAO parameterDAO = databaseUtility.getParameterDAO();
        parameterServiceTable.setList(parameterDAO.getAllParameter());

    }

    @Override
    public void onChange(ParameterServiceImpl parameterServiceImpl) {
        textId.setText(String.valueOf(parameterServiceImpl.getId()));
        textNamaParameter.setText(parameterServiceImpl.getNamaParameter());
        textNilai.setText(String.valueOf(parameterServiceImpl.getNilai()));
    }

    @Override
    public void onInsert(Parameter parameter) {
        parameterServiceTable.add(parameter);
    }

    @Override
    public void onUpdate(Parameter parameter) {
        int index = tblParameter.getSelectedRowCount();
        parameterServiceTable.set(index, parameter);
    }

    @Override
    public void onDelete() {
        int index = tblParameter.getSelectedRowCount();
        parameterServiceTable.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        Parameter parameter = parameterServiceTable.get(e.getFirstIndex());
        textId.setText(String.valueOf(parameter.getId()));
        textNamaParameter.setText(parameter.getNamaParameter());
        textNilai.setText(String.valueOf(parameter.getNilai()));
        labelId.setVisible(true);
        textId.setVisible(true);
        textNamaParameter.setEnabled(false);
        
    }
}
