/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gapabrikroti.view;

import gapabrikroti.controller.UserController;
import gapabrikroti.dao.UserDAO;
import gapabrikroti.error.UserException;
import gapabrikroti.model.User;
import gapabrikroti.service.UserService;
import gapabrikroti.service.UserServiceImpl;
import gapabrikroti.service.UserServiceTable;
import gapabrikroti.utility.databaseUtility;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



/**
 *
 * @author cvgs
 */
public class UserView extends javax.swing.JFrame implements UserService, ListSelectionListener  {

    /**
     * Creates new form UserView
     */
    
    private UserServiceTable userServiceTable;
    private UserServiceImpl userServiceImpl;
    private UserController userController;
        
    public UserView() throws SQLException, UserException {
        userServiceImpl = new UserServiceImpl();
        userServiceImpl.setUserService(this);

        userController = new UserController();
        userController.setUser(userServiceImpl);

        userServiceTable = new UserServiceTable();
        
        initComponents();
        
        tblUser.getSelectionModel().addListSelectionListener(this);
        tblUser.setModel(userServiceTable);

        loadTblUser();
    }

    public JTextField getTextHakakses() {
        return textHakakses;
    }

    public JTextField getTextPassword() {
        return textPassword;
    }

    public JTextField getTextUserName() {
        return textUserName;
    }

    public JTable getTblUser() {
        return tblUser;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        textUserName = new javax.swing.JTextField();
        textPassword = new javax.swing.JTextField();
        textHakakses = new javax.swing.JTextField();
        cmdSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdDelete = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        cmdUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textPassword.setText(" ");

        textHakakses.setText(" ");
        textHakakses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHakaksesActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        tblUser.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUser.setRowHeight(22);
        jScrollPane1.setViewportView(tblUser);

        jLabel1.setText("userName");

        jLabel2.setText("password");

        jLabel3.setText("hakAkses");

        cmdDelete.setText("Delete");
        cmdDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDeleteActionPerformed(evt);
            }
        });

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });

        cmdUpdate.setText("Update");
        cmdUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("User View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textHakakses)
                            .addComponent(textPassword)
                            .addComponent(textUserName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdReset)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHakakses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdDelete)
                    .addComponent(cmdReset)
                    .addComponent(cmdUpdate))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
        try {
            userController.insertUser(this);
            loadTblUser();
            tblUser.setVisible(false);
            tblUser.setVisible(true);
        } catch (SQLException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (UserException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void textHakaksesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHakaksesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHakaksesActionPerformed

    private void cmdUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateActionPerformed
        try {
            userController.updateUser(this);
            loadTblUser();
            tblUser.setVisible(false);
            tblUser.setVisible(true);
        } catch (SQLException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (UserException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdUpdateActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        try {
            userController.resetUser(this);
            loadTblUser();
            tblUser.setVisible(false);
            tblUser.setVisible(true);
        } catch (SQLException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (UserException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        }
        
    }//GEN-LAST:event_cmdResetActionPerformed

    private void cmdDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDeleteActionPerformed
        try {
            userController.deleteUser(this);
            loadTblUser();
            tblUser.setVisible(false);
            tblUser.setVisible(true);
        } catch (SQLException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        } catch (UserException exception) {
            Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, exception);
        }
    }//GEN-LAST:event_cmdDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UserException ex) {
                    Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDelete;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField textHakakses;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUserName;
    // End of variables declaration//GEN-END:variables
    
    private void loadTblUser() throws SQLException, UserException {
        UserDAO userDAO = databaseUtility.getUserDAO();
        userServiceTable.setList(userDAO.getAllUser());

    }

    @Override
    public void onChange(UserServiceImpl userServiceImpl) {
        textUserName.setText(userServiceImpl.getUserName());
        textPassword.setText(userServiceImpl.getPassword());
        textHakakses.setText(userServiceImpl.getHakAkses());
    }

    @Override
    public void onInsert(User user) {
        userServiceTable.add(user);
    }

    @Override
    public void onUpdate(User user) {
        int index = tblUser.getSelectedRowCount();
        userServiceTable.set(index, user);
    }

    @Override
    public void onDelete() {
        int index = tblUser.getSelectedRowCount();
        userServiceTable.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        User user = userServiceTable.get(e.getFirstIndex());
        textUserName.setText(user.getUserName());
        textPassword.setText(user.getPassword());
        textHakakses.setText(user.getHakAkses());
    }

}
